export const SOURCE_CURRENCY_CHANGED = "SOURCE_CURRENCY_CHANGED";
export const TARGET_CURRENCY_CHANGED = "TARGET_CURRENCY_CHANGED";
export const CHANGED_CURRENCY_DIRECTION = "CHANGED_CURRENCY_DIRECTION";
export const CURRENCIES_RESPONSE = "CURRENCIES_RESPONSE";
export const CHANGED_QUICK_CURRENCY_LIST = "CHANGED_QUICK_CURRENCY_LIST";
export const HIDED_ALERT = "HIDED_ALERT";
export const SHOW_ALERT = "SHOW_ALERT";